"""painel do destino por usuario

Guarda o nivel de cada no do Painel do Destino do jogador (task 4/17) — o que decide o custo
de foco real. `node_key` e opaco para o banco: o formato (`refine:fiber:4`, `spec:...`) e do
cliente, que conhece a forma da arvore, e ela nao e uniforme entre refino e craft.

O autogenerate quis derrubar `ix_item_busca_normalizada_trgm` de novo: ele nao reconhece o
indice GIN com `gin_trgm_ops` criado a mao. Removido daqui de proposito.

Revision ID: e59e948c3779
Revises: 1be9832e8ac9
Create Date: 2026-09-09 11:04:38.577731

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e59e948c3779"
down_revision: Union[str, Sequence[str], None] = "1be9832e8ac9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destiny_node",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("node_key", sa.String(length=64), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.CheckConstraint("level >= 0 AND level <= 100", name="ck_destiny_node_level"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "node_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("destiny_node")
    # ### end Alembic commands ###
